-- ================================================================
-- Restaurant Operating System - Comprehensive Database Migration
-- ================================================================

-- ================================================================
-- 1. CORE PLATFORM & ARCHITECTURE
-- ================================================================

-- Restaurants (Multi-tenant support)
CREATE TABLE IF NOT EXISTS restaurants (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    logo_url VARCHAR(512),
    email VARCHAR(255),
    phone VARCHAR(50),
    country VARCHAR(100),
    currency VARCHAR(10) DEFAULT 'USD',
    timezone VARCHAR(100) DEFAULT 'UTC',
    brand_color VARCHAR(20),
    status INT NOT NULL DEFAULT 1, -- 0=Inactive, 1=Active
    subscription_plan_id INT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL
);

-- Branches (Multi-branch support)
CREATE TABLE IF NOT EXISTS branches (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    address TEXT,
    phone VARCHAR(50),
    email VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    is_default BOOLEAN DEFAULT FALSE,
    status INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_branch_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);

-- Roles (RBAC)
CREATE TABLE IF NOT EXISTS roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    is_system_role BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_role_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);

-- Permissions
CREATE TABLE IF NOT EXISTS permissions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    resource VARCHAR(100) NOT NULL, -- menu, inventory, pos, reports, settings, etc.
    action VARCHAR(50) NOT NULL, -- create, read, update, delete, manage
    description TEXT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

-- Role Permissions (Many-to-Many)
CREATE TABLE IF NOT EXISTS role_permissions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id INT NOT NULL,
    permission_id INT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT fk_role_perm_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_role_perm_permission FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE,
    CONSTRAINT uk_role_permission UNIQUE (role_id, permission_id)
);

-- Staff
CREATE TABLE IF NOT EXISTS staff (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT,
    user_id INT,
    role_id INT NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    status INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_staff_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_staff_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL,
    CONSTRAINT fk_staff_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_staff_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE RESTRICT
);

-- ================================================================
-- 2. MENU MANAGEMENT
-- ================================================================

-- Menu Categories
CREATE TABLE IF NOT EXISTS menu_categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    display_order INT DEFAULT 0,
    status INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_menu_cat_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);

-- Menu Items
CREATE TABLE IF NOT EXISTS menu_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    category_id INT,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    cost DECIMAL(10, 2),
    sku VARCHAR(100),
    is_vegetarian BOOLEAN DEFAULT FALSE,
    is_halal BOOLEAN DEFAULT FALSE,
    is_available BOOLEAN DEFAULT TRUE,
    preparation_time INT, -- in minutes
    image_url VARCHAR(512),
    display_order INT DEFAULT 0,
    status INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_menu_item_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_menu_item_category FOREIGN KEY (category_id) REFERENCES menu_categories(id) ON DELETE SET NULL
);

-- ================================================================
-- 3. POS SYSTEM
-- ================================================================

-- POS Devices
CREATE TABLE IF NOT EXISTS pos_devices (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT NOT NULL,
    device_name VARCHAR(255) NOT NULL,
    machine_id VARCHAR(255) NOT NULL UNIQUE,
    device_type VARCHAR(50) DEFAULT 'POS', -- POS, KIOSK
    approval_status INT NOT NULL DEFAULT 0, -- 0=Pending, 1=Approved, 2=Declined
    is_active BOOLEAN DEFAULT TRUE,
    last_seen_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_pos_device_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_device_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE
);

-- Orders
CREATE TABLE IF NOT EXISTS orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT NOT NULL,
    pos_device_id INT,
    order_number VARCHAR(50) NOT NULL UNIQUE,
    order_token VARCHAR(20),
    order_type VARCHAR(20) NOT NULL, -- DINE_IN, TAKEAWAY, DELIVERY, QR, KIOSK
    order_source VARCHAR(20) NOT NULL, -- POS, QR, KIOSK, ONLINE
    table_id INT,
    customer_id INT,
    customer_name VARCHAR(255),
    customer_phone VARCHAR(50),
    customer_email VARCHAR(255),
    customer_address TEXT,
    guest_count INT,
    waiter_id INT,
    subtotal DECIMAL(10, 2) NOT NULL DEFAULT 0,
    tax_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
    delivery_fee DECIMAL(10, 2) DEFAULT 0,
    tip_amount DECIMAL(10, 2) DEFAULT 0,
    discount_amount DECIMAL(10, 2) DEFAULT 0,
    total_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
    payment_status INT NOT NULL DEFAULT 0, -- 0=Pending, 1=Paid, 2=Partial, 3=Refunded
    order_status INT NOT NULL DEFAULT 0, -- 0=Draft, 1=Confirmed, 2=Preparing, 3=Ready, 4=Completed, 5=Cancelled
    notes TEXT,
    cancelled_reason_id INT,
    cancelled_at TIMESTAMP(6) WITH TIME ZONE,
    cancelled_by INT,
    confirmed_at TIMESTAMP(6) WITH TIME ZONE,
    completed_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_order_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_pos_device FOREIGN KEY (pos_device_id) REFERENCES pos_devices(id) ON DELETE SET NULL,
    CONSTRAINT fk_order_waiter FOREIGN KEY (waiter_id) REFERENCES staff(id) ON DELETE SET NULL
);

-- Order Items
CREATE TABLE IF NOT EXISTS order_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    menu_item_id INT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    unit_price DECIMAL(10, 2) NOT NULL,
    total_price DECIMAL(10, 2) NOT NULL,
    tax_amount DECIMAL(10, 2) DEFAULT 0,
    special_instructions TEXT,
    status INT NOT NULL DEFAULT 0, -- 0=Pending, 1=Confirmed, 2=Cancelled
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_item_menu FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE RESTRICT
);

-- ================================================================
-- 4. TABLE & FLOOR MANAGEMENT
-- ================================================================

-- Floors
CREATE TABLE IF NOT EXISTS floors (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    display_order INT DEFAULT 0,
    status INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_floor_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_floor_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE
);

-- Tables
CREATE TABLE IF NOT EXISTS tables (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT NOT NULL,
    floor_id INT,
    table_number VARCHAR(50) NOT NULL,
    capacity INT NOT NULL DEFAULT 4,
    table_status INT NOT NULL DEFAULT 0, -- 0=Free, 1=Occupied, 2=Reserved, 3=Cleaning
    current_order_id INT,
    qr_code VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_table_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_table_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
    CONSTRAINT fk_table_floor FOREIGN KEY (floor_id) REFERENCES floors(id) ON DELETE SET NULL,
    CONSTRAINT fk_table_current_order FOREIGN KEY (current_order_id) REFERENCES orders(id) ON DELETE SET NULL
);

-- Add foreign key to orders table for table_id
ALTER TABLE orders ADD CONSTRAINT fk_order_table FOREIGN KEY (table_id) REFERENCES tables(id) ON DELETE SET NULL;

-- ================================================================
-- 5. KITCHEN ORDER TICKET (KOT) SYSTEM
-- ================================================================

-- Kitchens
CREATE TABLE IF NOT EXISTS kitchens (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    is_default BOOLEAN DEFAULT FALSE,
    status INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_kitchen_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_kitchen_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE
);

-- Kitchen Menu Item Mapping
CREATE TABLE IF NOT EXISTS kitchen_menu_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kitchen_id INT NOT NULL,
    menu_item_id INT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT fk_kitchen_menu_kitchen FOREIGN KEY (kitchen_id) REFERENCES kitchens(id) ON DELETE CASCADE,
    CONSTRAINT fk_kitchen_menu_item FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE CASCADE,
    CONSTRAINT uk_kitchen_menu_item UNIQUE (kitchen_id, menu_item_id)
);

-- KOT (Kitchen Order Tickets)
CREATE TABLE IF NOT EXISTS kots (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT NOT NULL,
    order_id INT NOT NULL,
    kitchen_id INT NOT NULL,
    kot_number VARCHAR(50) NOT NULL UNIQUE,
    kot_status INT NOT NULL DEFAULT 0, -- 0=Pending, 1=Cooking, 2=Ready, 3=Served, 4=Cancelled
    notes TEXT,
    cancelled_reason_id INT,
    cancelled_at TIMESTAMP(6) WITH TIME ZONE,
    started_at TIMESTAMP(6) WITH TIME ZONE,
    completed_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_kot_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_kot_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
    CONSTRAINT fk_kot_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_kot_kitchen FOREIGN KEY (kitchen_id) REFERENCES kitchens(id) ON DELETE RESTRICT
);

-- KOT Items
CREATE TABLE IF NOT EXISTS kot_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kot_id INT NOT NULL,
    order_item_id INT NOT NULL,
    menu_item_id INT NOT NULL,
    quantity INT NOT NULL,
    item_status INT NOT NULL DEFAULT 0, -- 0=Pending, 1=Cooking, 2=Ready, 3=Cancelled
    special_instructions TEXT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_kot_item_kot FOREIGN KEY (kot_id) REFERENCES kots(id) ON DELETE CASCADE,
    CONSTRAINT fk_kot_item_order_item FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE,
    CONSTRAINT fk_kot_item_menu FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE RESTRICT
);

-- ================================================================
-- 6. PRINTER MANAGEMENT
-- ================================================================

-- Printers
CREATE TABLE IF NOT EXISTS printers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    printer_type VARCHAR(50) NOT NULL, -- RECEIPT, KOT, LABEL
    ip_address VARCHAR(50),
    port INT,
    connection_type VARCHAR(50), -- NETWORK, USB, BLUETOOTH
    is_active BOOLEAN DEFAULT TRUE,
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_printer_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_printer_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE
);

-- Kitchen Printer Mapping
CREATE TABLE IF NOT EXISTS kitchen_printers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kitchen_id INT NOT NULL,
    printer_id INT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT fk_kitchen_printer_kitchen FOREIGN KEY (kitchen_id) REFERENCES kitchens(id) ON DELETE CASCADE,
    CONSTRAINT fk_kitchen_printer_printer FOREIGN KEY (printer_id) REFERENCES printers(id) ON DELETE CASCADE,
    CONSTRAINT uk_kitchen_printer UNIQUE (kitchen_id, printer_id)
);

-- POS Printer Mapping
CREATE TABLE IF NOT EXISTS pos_printers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pos_device_id INT NOT NULL,
    printer_id INT NOT NULL,
    printer_purpose VARCHAR(50) NOT NULL, -- RECEIPT, KOT
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT fk_pos_printer_pos FOREIGN KEY (pos_device_id) REFERENCES pos_devices(id) ON DELETE CASCADE,
    CONSTRAINT fk_pos_printer_printer FOREIGN KEY (printer_id) REFERENCES printers(id) ON DELETE CASCADE
);

-- ================================================================
-- 7. CASH REGISTER & CASH CONTROL
-- ================================================================

-- Cash Sessions
CREATE TABLE IF NOT EXISTS cash_sessions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT NOT NULL,
    pos_device_id INT NOT NULL,
    staff_id INT NOT NULL,
    session_number VARCHAR(50) NOT NULL UNIQUE,
    opening_balance DECIMAL(10, 2) NOT NULL DEFAULT 0,
    expected_closing_balance DECIMAL(10, 2) DEFAULT 0,
    actual_closing_balance DECIMAL(10, 2),
    discrepancy DECIMAL(10, 2) DEFAULT 0,
    total_cash_in DECIMAL(10, 2) DEFAULT 0,
    total_cash_out DECIMAL(10, 2) DEFAULT 0,
    total_safe_drop DECIMAL(10, 2) DEFAULT 0,
    session_status INT NOT NULL DEFAULT 1, -- 1=Open, 2=Closed, 3=Pending_Approval
    approved_by INT,
    approved_at TIMESTAMP(6) WITH TIME ZONE,
    notes TEXT,
    opened_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    closed_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_cash_session_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_cash_session_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
    CONSTRAINT fk_cash_session_pos FOREIGN KEY (pos_device_id) REFERENCES pos_devices(id) ON DELETE RESTRICT,
    CONSTRAINT fk_cash_session_staff FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE RESTRICT,
    CONSTRAINT fk_cash_session_approver FOREIGN KEY (approved_by) REFERENCES staff(id) ON DELETE SET NULL
);

-- Cash Transactions
CREATE TABLE IF NOT EXISTS cash_transactions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cash_session_id INT NOT NULL,
    transaction_type VARCHAR(50) NOT NULL, -- CASH_IN, CASH_OUT, SAFE_DROP
    amount DECIMAL(10, 2) NOT NULL,
    reason TEXT,
    created_by INT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT fk_cash_trans_session FOREIGN KEY (cash_session_id) REFERENCES cash_sessions(id) ON DELETE CASCADE,
    CONSTRAINT fk_cash_trans_creator FOREIGN KEY (created_by) REFERENCES staff(id) ON DELETE RESTRICT
);

-- Cash Denominations
CREATE TABLE IF NOT EXISTS cash_denominations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cash_session_id INT NOT NULL,
    denomination_type VARCHAR(50) NOT NULL, -- OPENING, CLOSING
    denomination_value DECIMAL(10, 2) NOT NULL,
    count INT NOT NULL DEFAULT 0,
    total DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT fk_cash_denom_session FOREIGN KEY (cash_session_id) REFERENCES cash_sessions(id) ON DELETE CASCADE
);

-- ================================================================
-- 8. BILLING & PAYMENTS
-- ================================================================

-- Payment Gateways
CREATE TABLE IF NOT EXISTS payment_gateways (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    gateway_name VARCHAR(100) NOT NULL, -- STRIPE, PAYPAL, XENDIT, EPAY
    gateway_type VARCHAR(50) NOT NULL, -- ONLINE, OFFLINE, QR
    api_key VARCHAR(512),
    secret_key VARCHAR(512),
    webhook_secret VARCHAR(512),
    qr_code_url VARCHAR(512),
    is_active BOOLEAN DEFAULT FALSE,
    configuration JSONB, -- For storing additional gateway-specific configs
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_payment_gateway_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);

-- Payments
CREATE TABLE IF NOT EXISTS payments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    order_id INT NOT NULL,
    payment_gateway_id INT,
    payment_method VARCHAR(50) NOT NULL, -- CASH, CARD, QR, ONLINE, MIXED
    payment_status INT NOT NULL DEFAULT 0, -- 0=Pending, 1=Completed, 2=Failed, 3=Refunded
    amount DECIMAL(10, 2) NOT NULL,
    transaction_id VARCHAR(255),
    gateway_response JSONB,
    notes TEXT,
    paid_at TIMESTAMP(6) WITH TIME ZONE,
    refunded_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_payment_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_gateway FOREIGN KEY (payment_gateway_id) REFERENCES payment_gateways(id) ON DELETE SET NULL
);

-- Mixed Payment Details (for orders with multiple payment methods)
CREATE TABLE IF NOT EXISTS payment_splits (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id INT NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT fk_payment_split_payment FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE CASCADE
);

-- ================================================================
-- 9. TAX & COMPLIANCE
-- ================================================================

-- Tax Configurations
CREATE TABLE IF NOT EXISTS tax_configurations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    tax_name VARCHAR(100) NOT NULL,
    tax_type VARCHAR(50) NOT NULL, -- PERCENTAGE, FIXED
    tax_rate DECIMAL(5, 2), -- For percentage-based
    tax_amount DECIMAL(10, 2), -- For fixed-amount
    apply_to VARCHAR(50) NOT NULL, -- ORDER, ITEM
    is_inclusive BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    show_on_receipt BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_tax_config_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);

-- ================================================================
-- 10. INVENTORY MANAGEMENT (RAW MATERIALS)
-- ================================================================

-- Inventory Categories
CREATE TABLE IF NOT EXISTS inventory_categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_inv_cat_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);

-- Units of Measurement
CREATE TABLE IF NOT EXISTS units (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE, -- kg, g, L, ml, pc, box, etc.
    abbreviation VARCHAR(10) NOT NULL,
    unit_type VARCHAR(50), -- WEIGHT, VOLUME, COUNT
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

-- Inventory Items (Raw Materials)
CREATE TABLE IF NOT EXISTS inventory_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    category_id INT,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    sku VARCHAR(100),
    unit_id INT NOT NULL,
    current_stock DECIMAL(15, 3) DEFAULT 0,
    minimum_stock DECIMAL(15, 3) DEFAULT 0,
    unit_cost DECIMAL(10, 2) DEFAULT 0,
    allow_negative_stock BOOLEAN DEFAULT FALSE,
    status INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_inv_item_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_inv_item_category FOREIGN KEY (category_id) REFERENCES inventory_categories(id) ON DELETE SET NULL,
    CONSTRAINT fk_inv_item_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE RESTRICT
);

-- Stock Movements (Audit Trail)
CREATE TABLE IF NOT EXISTS stock_movements (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    inventory_item_id INT NOT NULL,
    movement_type VARCHAR(50) NOT NULL, -- IN, OUT, ADJUSTMENT, PRODUCTION, WASTE
    quantity DECIMAL(15, 3) NOT NULL,
    reference_type VARCHAR(50), -- PURCHASE_ORDER, BATCH_PRODUCTION, MANUAL
    reference_id INT,
    notes TEXT,
    created_by INT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT fk_stock_move_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_move_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_move_creator FOREIGN KEY (created_by) REFERENCES staff(id) ON DELETE RESTRICT
);

-- ================================================================
-- 11. RECIPE MANAGEMENT
-- ================================================================

-- Recipes
CREATE TABLE IF NOT EXISTS recipes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    menu_item_id INT,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    preparation_time INT, -- in minutes
    recipe_cost DECIMAL(10, 2) DEFAULT 0,
    yield_quantity DECIMAL(10, 2) DEFAULT 1,
    yield_unit VARCHAR(50),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_recipe_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_menu_item FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE SET NULL
);

-- Recipe Ingredients
CREATE TABLE IF NOT EXISTS recipe_ingredients (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id INT NOT NULL,
    inventory_item_id INT NOT NULL,
    quantity DECIMAL(15, 3) NOT NULL,
    unit_id INT NOT NULL,
    ingredient_cost DECIMAL(10, 2) DEFAULT 0,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_recipe_ing_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_ing_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE RESTRICT,
    CONSTRAINT fk_recipe_ing_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE RESTRICT
);

-- ================================================================
-- 12. BATCH RECIPE & PRODUCTION MANAGEMENT
-- ================================================================

-- Batch Recipes
CREATE TABLE IF NOT EXISTS batch_recipes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    output_inventory_item_id INT, -- What inventory item this produces
    yield_quantity DECIMAL(15, 3) NOT NULL,
    yield_unit_id INT NOT NULL,
    batch_cost DECIMAL(10, 2) DEFAULT 0,
    cost_per_unit DECIMAL(10, 2) DEFAULT 0,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_batch_recipe_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_batch_recipe_output FOREIGN KEY (output_inventory_item_id) REFERENCES inventory_items(id) ON DELETE SET NULL,
    CONSTRAINT fk_batch_recipe_unit FOREIGN KEY (yield_unit_id) REFERENCES units(id) ON DELETE RESTRICT
);

-- Batch Recipe Ingredients
CREATE TABLE IF NOT EXISTS batch_recipe_ingredients (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_recipe_id INT NOT NULL,
    inventory_item_id INT NOT NULL,
    quantity DECIMAL(15, 3) NOT NULL,
    unit_id INT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT fk_batch_ing_recipe FOREIGN KEY (batch_recipe_id) REFERENCES batch_recipes(id) ON DELETE CASCADE,
    CONSTRAINT fk_batch_ing_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE RESTRICT,
    CONSTRAINT fk_batch_ing_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE RESTRICT
);

-- Batch Productions
CREATE TABLE IF NOT EXISTS batch_productions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT NOT NULL,
    batch_recipe_id INT NOT NULL,
    batch_number VARCHAR(50) NOT NULL UNIQUE,
    production_date DATE NOT NULL,
    quantity_produced DECIMAL(15, 3) NOT NULL,
    unit_id INT NOT NULL,
    total_cost DECIMAL(10, 2) DEFAULT 0,
    cost_per_unit DECIMAL(10, 2) DEFAULT 0,
    expiry_date DATE,
    status INT NOT NULL DEFAULT 1, -- 1=Active, 2=Consumed, 3=Expired, 4=Wasted
    notes TEXT,
    produced_by INT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_batch_prod_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_batch_prod_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
    CONSTRAINT fk_batch_prod_recipe FOREIGN KEY (batch_recipe_id) REFERENCES batch_recipes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_batch_prod_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE RESTRICT,
    CONSTRAINT fk_batch_prod_producer FOREIGN KEY (produced_by) REFERENCES staff(id) ON DELETE RESTRICT
);

-- Batch Inventory (Track individual batches)
CREATE TABLE IF NOT EXISTS batch_inventory (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_production_id INT NOT NULL,
    inventory_item_id INT NOT NULL,
    current_quantity DECIMAL(15, 3) NOT NULL,
    initial_quantity DECIMAL(15, 3) NOT NULL,
    unit_id INT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_batch_inv_production FOREIGN KEY (batch_production_id) REFERENCES batch_productions(id) ON DELETE CASCADE,
    CONSTRAINT fk_batch_inv_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE CASCADE,
    CONSTRAINT fk_batch_inv_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE RESTRICT
);

-- ================================================================
-- 13. PROCUREMENT & SUPPLIER MANAGEMENT
-- ================================================================

-- Suppliers
CREATE TABLE IF NOT EXISTS suppliers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    contact_person VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(50),
    address TEXT,
    tax_id VARCHAR(100),
    payment_terms TEXT,
    status INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_supplier_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);

-- Purchase Orders
CREATE TABLE IF NOT EXISTS purchase_orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT NOT NULL,
    supplier_id INT NOT NULL,
    po_number VARCHAR(50) NOT NULL UNIQUE,
    order_date DATE NOT NULL,
    expected_delivery_date DATE,
    total_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
    paid_amount DECIMAL(10, 2) DEFAULT 0,
    po_status INT NOT NULL DEFAULT 0, -- 0=Draft, 1=Sent, 2=Partially_Received, 3=Received, 4=Cancelled
    notes TEXT,
    created_by INT NOT NULL,
    approved_by INT,
    approved_at TIMESTAMP(6) WITH TIME ZONE,
    received_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_po_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_po_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
    CONSTRAINT fk_po_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_po_creator FOREIGN KEY (created_by) REFERENCES staff(id) ON DELETE RESTRICT,
    CONSTRAINT fk_po_approver FOREIGN KEY (approved_by) REFERENCES staff(id) ON DELETE SET NULL
);

-- Purchase Order Items
CREATE TABLE IF NOT EXISTS purchase_order_items (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id INT NOT NULL,
    inventory_item_id INT NOT NULL,
    quantity_ordered DECIMAL(15, 3) NOT NULL,
    quantity_received DECIMAL(15, 3) DEFAULT 0,
    unit_id INT NOT NULL,
    unit_cost DECIMAL(10, 2) NOT NULL,
    total_cost DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_po_item_po FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_po_item_inv FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE RESTRICT,
    CONSTRAINT fk_po_item_unit FOREIGN KEY (unit_id) REFERENCES units(id) ON DELETE RESTRICT
);

-- ================================================================
-- 14. DELIVERY MANAGEMENT
-- ================================================================

-- Delivery Zones
CREATE TABLE IF NOT EXISTS delivery_zones (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT NOT NULL,
    zone_name VARCHAR(255) NOT NULL,
    postal_codes TEXT, -- Comma-separated or JSON array
    delivery_fee DECIMAL(10, 2) NOT NULL,
    minimum_order_amount DECIMAL(10, 2) DEFAULT 0,
    free_delivery_threshold DECIMAL(10, 2),
    estimated_time INT, -- in minutes
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_delivery_zone_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_delivery_zone_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE
);

-- Delivery Settings
CREATE TABLE IF NOT EXISTS delivery_settings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT NOT NULL,
    fixed_delivery_fee DECIMAL(10, 2) DEFAULT 0,
    enable_distance_based_fee BOOLEAN DEFAULT FALSE,
    fee_per_km DECIMAL(10, 2) DEFAULT 0,
    maximum_delivery_radius_km DECIMAL(5, 2), -- in km
    free_delivery_over_amount DECIMAL(10, 2),
    free_delivery_within_radius_km DECIMAL(5, 2),
    delivery_start_time TIME,
    delivery_end_time TIME,
    is_24_7_delivery BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_delivery_settings_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_delivery_settings_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
    CONSTRAINT uk_delivery_settings_branch UNIQUE (restaurant_id, branch_id)
);

-- ================================================================
-- 15. RESERVATION SYSTEM
-- ================================================================

-- Reservation Slots
CREATE TABLE IF NOT EXISTS reservation_slots (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT NOT NULL,
    day_of_week INT NOT NULL, -- 0=Sunday, 1=Monday, ..., 6=Saturday
    meal_period VARCHAR(50), -- BREAKFAST, LUNCH, DINNER
    slot_time TIME NOT NULL,
    capacity INT NOT NULL,
    slot_interval INT DEFAULT 60, -- in minutes (30 or 60)
    disable_before_minutes INT DEFAULT 30, -- Auto-disable slot X minutes before
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_res_slot_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_res_slot_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE
);

-- Reservations
CREATE TABLE IF NOT EXISTS reservations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT NOT NULL,
    reservation_slot_id INT,
    customer_id INT,
    customer_name VARCHAR(255) NOT NULL,
    customer_phone VARCHAR(50) NOT NULL,
    customer_email VARCHAR(255),
    party_size INT NOT NULL,
    reservation_date DATE NOT NULL,
    reservation_time TIME NOT NULL,
    reservation_status INT NOT NULL DEFAULT 0, -- 0=Pending, 1=Confirmed, 2=Seated, 3=Completed, 4=Cancelled, 5=No_Show
    special_requests TEXT,
    table_id INT,
    created_by_admin BOOLEAN DEFAULT FALSE,
    cancelled_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_reservation_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_reservation_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
    CONSTRAINT fk_reservation_slot FOREIGN KEY (reservation_slot_id) REFERENCES reservation_slots(id) ON DELETE SET NULL,
    CONSTRAINT fk_reservation_table FOREIGN KEY (table_id) REFERENCES tables(id) ON DELETE SET NULL
);

-- Reservation Settings
CREATE TABLE IF NOT EXISTS reservation_settings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT NOT NULL,
    minimum_party_size INT DEFAULT 1,
    maximum_party_size INT DEFAULT 20,
    require_customer_login BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_res_settings_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_res_settings_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
    CONSTRAINT uk_res_settings_branch UNIQUE (restaurant_id, branch_id)
);

-- ================================================================
-- 16. CANCELLATION & AUDIT CONTROL
-- ================================================================

-- Cancellation Reasons
CREATE TABLE IF NOT EXISTS cancellation_reasons (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    reason TEXT NOT NULL,
    applies_to VARCHAR(20) NOT NULL, -- ORDER, KOT, BOTH
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_cancel_reason_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE
);

-- Add foreign keys for cancellation reasons
ALTER TABLE orders ADD CONSTRAINT fk_order_cancel_reason FOREIGN KEY (cancelled_reason_id) REFERENCES cancellation_reasons(id) ON DELETE SET NULL;
ALTER TABLE kots ADD CONSTRAINT fk_kot_cancel_reason FOREIGN KEY (cancelled_reason_id) REFERENCES cancellation_reasons(id) ON DELETE SET NULL;

-- ================================================================
-- 17. CUSTOMER MANAGEMENT & ONLINE ORDERING
-- ================================================================

-- Customers
CREATE TABLE IF NOT EXISTS customers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    user_id INT,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100),
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    default_address TEXT,
    city VARCHAR(100),
    postal_code VARCHAR(20),
    loyalty_points INT DEFAULT 0,
    total_orders INT DEFAULT 0,
    total_spent DECIMAL(10, 2) DEFAULT 0,
    status INT NOT NULL DEFAULT 1,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_customer_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_customer_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Add foreign key to orders
ALTER TABLE orders ADD CONSTRAINT fk_order_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL;

-- Customer Addresses
CREATE TABLE IF NOT EXISTS customer_addresses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL,
    address_type VARCHAR(50) DEFAULT 'HOME', -- HOME, WORK, OTHER
    address_line1 TEXT NOT NULL,
    address_line2 TEXT,
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_customer_addr_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);

-- Online Ordering Settings
CREATE TABLE IF NOT EXISTS online_ordering_settings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT,
    is_enabled BOOLEAN DEFAULT TRUE,
    require_customer_login BOOLEAN DEFAULT FALSE,
    qr_order_radius_km DECIMAL(5, 2),
    pickup_days_range INT DEFAULT 7,
    auto_confirm_orders BOOLEAN DEFAULT FALSE,
    enable_tips BOOLEAN DEFAULT TRUE,
    show_veg_items BOOLEAN DEFAULT TRUE,
    show_halal_items BOOLEAN DEFAULT TRUE,
    header_text TEXT,
    footer_text TEXT,
    terms_and_conditions TEXT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_online_settings_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_online_settings_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE
);

-- ================================================================
-- 18. SELF-SERVICE KIOSK SYSTEM
-- ================================================================

-- Kiosks
CREATE TABLE IF NOT EXISTS kiosks (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT NOT NULL,
    kiosk_code VARCHAR(50) NOT NULL UNIQUE,
    kiosk_name VARCHAR(255) NOT NULL,
    require_customer_info BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    last_activity_at TIMESTAMP(6) WITH TIME ZONE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_kiosk_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_kiosk_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE
);

-- ================================================================
-- 19. RECEIPT CUSTOMIZATION
-- ================================================================

-- Receipt Settings
CREATE TABLE IF NOT EXISTS receipt_settings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT,
    show_customer_name BOOLEAN DEFAULT TRUE,
    show_customer_address BOOLEAN DEFAULT TRUE,
    show_customer_phone BOOLEAN DEFAULT TRUE,
    show_waiter_name BOOLEAN DEFAULT TRUE,
    show_table_number BOOLEAN DEFAULT TRUE,
    show_guest_count BOOLEAN DEFAULT TRUE,
    show_order_type BOOLEAN DEFAULT TRUE,
    show_payment_details BOOLEAN DEFAULT TRUE,
    show_payment_qr BOOLEAN DEFAULT FALSE,
    show_tax_info BOOLEAN DEFAULT TRUE,
    header_text TEXT,
    footer_text TEXT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_receipt_settings_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_receipt_settings_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE
);

-- ================================================================
-- 20. SAAS BILLING & SUBSCRIPTION ENGINE
-- ================================================================

-- Subscription Plans
CREATE TABLE IF NOT EXISTS subscription_plans (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_name VARCHAR(100) NOT NULL,
    plan_type VARCHAR(50) NOT NULL, -- FREE, STARTER, PROFESSIONAL, ENTERPRISE
    billing_cycle VARCHAR(50), -- MONTHLY, YEARLY, LIFETIME
    price DECIMAL(10, 2) NOT NULL DEFAULT 0,
    max_branches INT,
    max_pos_devices INT,
    max_staff INT,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL
);

-- Plan Features
CREATE TABLE IF NOT EXISTS plan_features (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_plan_id INT NOT NULL,
    feature_name VARCHAR(100) NOT NULL,
    feature_key VARCHAR(100) NOT NULL, -- theme_customization, advanced_reporting, etc.
    is_enabled BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT fk_plan_feature_plan FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plans(id) ON DELETE CASCADE
);

-- Add foreign key to restaurants
ALTER TABLE restaurants ADD CONSTRAINT fk_restaurant_plan FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plans(id) ON DELETE SET NULL;

-- Subscriptions
CREATE TABLE IF NOT EXISTS subscriptions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    subscription_plan_id INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    billing_cycle VARCHAR(50),
    amount DECIMAL(10, 2) NOT NULL,
    payment_status INT NOT NULL DEFAULT 0, -- 0=Pending, 1=Paid, 2=Failed
    subscription_status INT NOT NULL DEFAULT 1, -- 1=Active, 2=Expired, 3=Cancelled
    payment_method VARCHAR(50), -- ONLINE, OFFLINE
    transaction_id VARCHAR(255),
    auto_renew BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_subscription_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_subscription_plan FOREIGN KEY (subscription_plan_id) REFERENCES subscription_plans(id) ON DELETE RESTRICT
);

-- Payment History (for subscriptions and offline payments)
CREATE TABLE IF NOT EXISTS payment_history (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    subscription_id INT,
    amount DECIMAL(10, 2) NOT NULL,
    payment_method VARCHAR(50),
    payment_status INT NOT NULL DEFAULT 0,
    transaction_id VARCHAR(255),
    payment_date TIMESTAMP(6) WITH TIME ZONE,
    notes TEXT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT fk_payment_history_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_history_subscription FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE SET NULL
);

-- ================================================================
-- 21. SYSTEM SETTINGS & CONFIGURATIONS
-- ================================================================

-- System Settings (Key-Value Store)
CREATE TABLE IF NOT EXISTS system_settings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT,
    setting_key VARCHAR(100) NOT NULL,
    setting_value TEXT,
    setting_type VARCHAR(50), -- STRING, NUMBER, BOOLEAN, JSON
    setting_category VARCHAR(50), -- GENERAL, EMAIL, ORDER, KOT, DELIVERY, etc.
    description TEXT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_sys_settings_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_sys_settings_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
    CONSTRAINT uk_setting_key_restaurant_branch UNIQUE (restaurant_id, branch_id, setting_key)
);

-- Email Templates
CREATE TABLE IF NOT EXISTS email_templates (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    template_name VARCHAR(100) NOT NULL,
    template_key VARCHAR(100) NOT NULL, -- ORDER_CONFIRMATION, RESERVATION_CONFIRMED, etc.
    subject VARCHAR(255) NOT NULL,
    body_html TEXT NOT NULL,
    body_text TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_email_template_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT uk_email_template_key UNIQUE (restaurant_id, template_key)
);

-- ================================================================
-- 22. AUDIT & LOGGING
-- ================================================================

-- Audit Logs
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT,
    user_id INT,
    staff_id INT,
    action VARCHAR(100) NOT NULL, -- CREATE, UPDATE, DELETE, LOGIN, LOGOUT, etc.
    entity_type VARCHAR(100), -- ORDER, KOT, PAYMENT, INVENTORY, etc.
    entity_id INT,
    old_values JSONB,
    new_values JSONB,
    ip_address VARCHAR(50),
    user_agent TEXT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT fk_audit_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_audit_staff FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE SET NULL
);

-- ================================================================
-- 23. ANALYTICS & REPORTS (Foundation Tables)
-- ================================================================

-- Daily Sales Summary
CREATE TABLE IF NOT EXISTS daily_sales_summary (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    branch_id INT NOT NULL,
    summary_date DATE NOT NULL,
    total_orders INT DEFAULT 0,
    total_revenue DECIMAL(10, 2) DEFAULT 0,
    total_tax DECIMAL(10, 2) DEFAULT 0,
    total_tips DECIMAL(10, 2) DEFAULT 0,
    total_discounts DECIMAL(10, 2) DEFAULT 0,
    dine_in_orders INT DEFAULT 0,
    takeaway_orders INT DEFAULT 0,
    delivery_orders INT DEFAULT 0,
    online_orders INT DEFAULT 0,
    cancelled_orders INT DEFAULT 0,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP(6) WITH TIME ZONE NULL,
    CONSTRAINT fk_daily_sales_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_daily_sales_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
    CONSTRAINT uk_daily_sales_date UNIQUE (restaurant_id, branch_id, summary_date)
);

-- ================================================================
-- 24. NOTIFICATIONS
-- ================================================================

-- Notifications
CREATE TABLE IF NOT EXISTS notifications (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id INT NOT NULL,
    user_id INT,
    staff_id INT,
    notification_type VARCHAR(50) NOT NULL, -- ORDER, RESERVATION, INVENTORY, SYSTEM
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    reference_type VARCHAR(50),
    reference_id INT,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT fk_notification_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_notification_staff FOREIGN KEY (staff_id) REFERENCES staff(id) ON DELETE CASCADE
);

-- ================================================================
-- INDEXES FOR PERFORMANCE OPTIMIZATION
-- ================================================================

-- Core Platform Indexes
CREATE INDEX idx_branches_restaurant ON branches(restaurant_id);
CREATE INDEX idx_staff_restaurant ON staff(restaurant_id);
CREATE INDEX idx_staff_branch ON staff(branch_id);
CREATE INDEX idx_staff_role ON staff(role_id);

-- Menu Indexes
CREATE INDEX idx_menu_categories_restaurant ON menu_categories(restaurant_id);
CREATE INDEX idx_menu_items_restaurant ON menu_items(restaurant_id);
CREATE INDEX idx_menu_items_category ON menu_items(category_id);
CREATE INDEX idx_menu_items_status ON menu_items(status);

-- POS & Orders Indexes
CREATE INDEX idx_pos_devices_restaurant ON pos_devices(restaurant_id);
CREATE INDEX idx_pos_devices_branch ON pos_devices(branch_id);
CREATE INDEX idx_orders_restaurant ON orders(restaurant_id);
CREATE INDEX idx_orders_branch ON orders(branch_id);
CREATE INDEX idx_orders_order_number ON orders(order_number);
CREATE INDEX idx_orders_status ON orders(order_status);
CREATE INDEX idx_orders_created_at ON orders(created_at);
CREATE INDEX idx_order_items_order ON order_items(order_id);
CREATE INDEX idx_order_items_menu_item ON order_items(menu_item_id);

-- Table Management Indexes
CREATE INDEX idx_tables_restaurant ON tables(restaurant_id);
CREATE INDEX idx_tables_branch ON tables(branch_id);
CREATE INDEX idx_tables_status ON tables(table_status);

-- KOT Indexes
CREATE INDEX idx_kitchens_restaurant ON kitchens(restaurant_id);
CREATE INDEX idx_kitchens_branch ON kitchens(branch_id);
CREATE INDEX idx_kots_restaurant ON kots(restaurant_id);
CREATE INDEX idx_kots_order ON kots(order_id);
CREATE INDEX idx_kots_kitchen ON kots(kitchen_id);
CREATE INDEX idx_kots_status ON kots(kot_status);
CREATE INDEX idx_kot_items_kot ON kot_items(kot_id);

-- Printer Indexes
CREATE INDEX idx_printers_restaurant ON printers(restaurant_id);
CREATE INDEX idx_printers_branch ON printers(branch_id);

-- Cash Register Indexes
CREATE INDEX idx_cash_sessions_restaurant ON cash_sessions(restaurant_id);
CREATE INDEX idx_cash_sessions_branch ON cash_sessions(branch_id);
CREATE INDEX idx_cash_sessions_pos ON cash_sessions(pos_device_id);
CREATE INDEX idx_cash_sessions_status ON cash_sessions(session_status);

-- Payment Indexes
CREATE INDEX idx_payments_restaurant ON payments(restaurant_id);
CREATE INDEX idx_payments_order ON payments(order_id);
CREATE INDEX idx_payments_status ON payments(payment_status);

-- Inventory Indexes
CREATE INDEX idx_inventory_items_restaurant ON inventory_items(restaurant_id);
CREATE INDEX idx_inventory_items_category ON inventory_items(category_id);
CREATE INDEX idx_stock_movements_restaurant ON stock_movements(restaurant_id);
CREATE INDEX idx_stock_movements_item ON stock_movements(inventory_item_id);
CREATE INDEX idx_stock_movements_created_at ON stock_movements(created_at);

-- Recipe Indexes
CREATE INDEX idx_recipes_restaurant ON recipes(restaurant_id);
CREATE INDEX idx_recipes_menu_item ON recipes(menu_item_id);
CREATE INDEX idx_recipe_ingredients_recipe ON recipe_ingredients(recipe_id);

-- Batch Production Indexes
CREATE INDEX idx_batch_productions_restaurant ON batch_productions(restaurant_id);
CREATE INDEX idx_batch_productions_recipe ON batch_productions(batch_recipe_id);
CREATE INDEX idx_batch_productions_date ON batch_productions(production_date);

-- Procurement Indexes
CREATE INDEX idx_suppliers_restaurant ON suppliers(restaurant_id);
CREATE INDEX idx_purchase_orders_restaurant ON purchase_orders(restaurant_id);
CREATE INDEX idx_purchase_orders_supplier ON purchase_orders(supplier_id);
CREATE INDEX idx_purchase_orders_status ON purchase_orders(po_status);

-- Reservation Indexes
CREATE INDEX idx_reservations_restaurant ON reservations(restaurant_id);
CREATE INDEX idx_reservations_branch ON reservations(branch_id);
CREATE INDEX idx_reservations_date ON reservations(reservation_date);
CREATE INDEX idx_reservations_status ON reservations(reservation_status);

-- Customer Indexes
CREATE INDEX idx_customers_restaurant ON customers(restaurant_id);
CREATE INDEX idx_customers_email ON customers(email);
CREATE INDEX idx_customers_phone ON customers(phone);

-- Subscription Indexes
CREATE INDEX idx_subscriptions_restaurant ON subscriptions(restaurant_id);
CREATE INDEX idx_subscriptions_status ON subscriptions(subscription_status);

-- Audit Indexes
CREATE INDEX idx_audit_logs_restaurant ON audit_logs(restaurant_id);
CREATE INDEX idx_audit_logs_user ON audit_logs(user_id);
CREATE INDEX idx_audit_logs_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at);

-- Notification Indexes
CREATE INDEX idx_notifications_restaurant ON notifications(restaurant_id);
CREATE INDEX idx_notifications_user ON notifications(user_id);
CREATE INDEX idx_notifications_staff ON notifications(staff_id);
CREATE INDEX idx_notifications_is_read ON notifications(is_read);

-- ================================================================
-- INSERT DEFAULT DATA
-- ================================================================

-- Insert Default Units
INSERT INTO units (name, abbreviation, unit_type) VALUES
('Kilogram', 'kg', 'WEIGHT'),
('Gram', 'g', 'WEIGHT'),
('Liter', 'L', 'VOLUME'),
('Milliliter', 'ml', 'VOLUME'),
('Piece', 'pc', 'COUNT'),
('Box', 'box', 'COUNT'),
('Dozen', 'doz', 'COUNT'),
('Cup', 'cup', 'VOLUME'),
('Tablespoon', 'tbsp', 'VOLUME'),
('Teaspoon', 'tsp', 'VOLUME'),
('Ounce', 'oz', 'WEIGHT'),
('Pound', 'lb', 'WEIGHT')
ON CONFLICT (name) DO NOTHING;

-- Insert Default Permissions
INSERT INTO permissions (name, resource, action, description) VALUES
('view_menu', 'menu', 'read', 'View menu items and categories'),
('manage_menu', 'menu', 'manage', 'Full access to menu management'),
('view_orders', 'orders', 'read', 'View orders'),
('create_orders', 'orders', 'create', 'Create new orders'),
('manage_orders', 'orders', 'manage', 'Full access to order management'),
('view_inventory', 'inventory', 'read', 'View inventory'),
('manage_inventory', 'inventory', 'manage', 'Full access to inventory management'),
('view_reports', 'reports', 'read', 'View reports and analytics'),
('manage_reports', 'reports', 'manage', 'Full access to reports'),
('view_settings', 'settings', 'read', 'View system settings'),
('manage_settings', 'settings', 'manage', 'Full access to system settings'),
('manage_staff', 'staff', 'manage', 'Manage staff and roles'),
('view_pos', 'pos', 'read', 'Access POS system'),
('manage_pos', 'pos', 'manage', 'Manage POS devices and configuration'),
('view_kitchen', 'kitchen', 'read', 'View KOT and kitchen orders'),
('manage_kitchen', 'kitchen', 'manage', 'Manage kitchen operations'),
('view_cash_register', 'cash_register', 'read', 'View cash register'),
('manage_cash_register', 'cash_register', 'manage', 'Manage cash register operations'),
('view_reservations', 'reservations', 'read', 'View reservations'),
('manage_reservations', 'reservations', 'manage', 'Manage reservations'),
('view_customers', 'customers', 'read', 'View customer information'),
('manage_customers', 'customers', 'manage', 'Manage customers')
ON CONFLICT (name) DO NOTHING;

-- ================================================================
-- END OF MIGRATION
-- ================================================================
